package-lock.json, package.json, server/logger.js
…ing when a transport connection fails (papertrail)
=> Added exception handler for winston logger to prevent app from crash

client/start.js, package-lock.json, package.json
=> Add registerStoryShare and setMemberId in app object

isomorphic/component.js
Pass key to the rendered components
- to support unmounting and mounting of component if key changes
=> Fix section-page loadmore bug

client/start.js
Sets SEO meta title and then fallbacks to story title
=> quintype/quintype-node-components#31 Add SEO metatitle with fallback

assetify/client.js, package-lock.json, package.json
- using negative lookahead to identify `app` which is not followed by `\`
=> fix(identify public path): use regex to identify public path

client/service-worker-helper.js, package-lock.json, package.json, server/handlers/generate-service-worker.js, server/handlers/isomorphic-handler.js, server/routes.js, test/integration/shell-test.js
Also added logic to take maximum configVersion(time-stamp) out of Page-builder config and secret-mode config
=> fix(service-worker): Fix service-worker update and added cache-tag to service-worker response

package-lock.json, package.json, server/amp-helpers.js, server/handlers/amp-handler.js, server/routes.js, test/integration/amp-handler-test.js
https://github.com/quintype/quintype-amp/issues/77
=> Infinite scroll

package-lock.json, package.json, server/amp-helpers.js
https://github.com/quintype/quintype-amp/issues/224
=> Amp infinite scr exclude paid

package-lock.json, package.json, server/routes.js
Adds amp optimizer middleware and bumps amp lib to pull in version containing other perf optimizations
=> Amp optimizer

package-lock.json, package.json
https://github.com/quintype/quintype-amp/issues/258
=> fix(amp): add slot after every card in generic story

package-lock.json, package.json
https://github.com/quintype/quintype-amp/pull/265
=> fix(amp): do not show pending amp elements - bad UX

package-lock.json, package.json
https://github.com/quintype/quintype-amp/issues/278
=> fix(amp): fix for barandbench prod issue

server/handlers/isomorphic-handler.js, server/logger.js, test/unit/logger-test.js
https://github.com/quintype/ace-planning/issues/48
=> Feat: Support Logging to stdout

package-lock.json, package.json, server/redirect-url-helper.js, server/routes.js, test/integration/url-redirect-test.js
https://github.com/quintype/ace-planning/issues/15
=> (Feat): Redirect url

server/routes.js, test/integration/sketches-proxy-test.js
https://github.com/quintype/ace-planning/issues/53
=> Feat : Support new sitemap url

package-lock.json, package.json
https://github.com/quintype/quintype-amp/pull/286
=> fix(amp): hero image smaller than recommended size

client/start.js, package-lock.json, package.json
https://github.com/quintype/ace-planning/issues/11
=> (Feat) client/start.js -> support for custom metadata

package-lock.json, package.json, server/handlers/isomorphic-handler.js, test/integration/isomorphic-handler-test.js
https://github.com/quintype/ace-planning/issues/66
=> fix(remove preload route-data)

server/handlers/cdn-caching.js, test/integration/isomorphic-handler-test.js
https://github.com/quintype/ace-planning/issues/46
=> feat: Add content security policy

client/start.js, package-lock.json, package.json
On clicking on the forward and back button from the browser, the path is getting undefined in the `navigateToPage()` function of the `client/start.js` file of Quintype/node-framework. so I have added a defensive check there.
(Ticket) [https://github.com/quintype/ace-planning/issues/91]
1. Tested it on locally with a node framework.
2. Published a beta version and tested it on malibu staging.
=> (Fix) Browser navigation : Browser back and forward button does not change the content.

package-lock.json, package.json
Bump amplib version to fix issue
https://github.com/quintype/quintype-amp/issues/308
=> Amp chartbeat fix

package-lock.json, package.json
=> fix(amp): bump amplib to take visual story fixes

package-lock.json, package.json, server/amp/handlers/story-page.js, server/handlers/cdn-caching.js, server/handlers/custom-route-handler.js, server/handlers/isomorphic-handler.js, server/handlers/story-redirect.js, server/routes.js, server/visual-stories.js, test/integration/isomorphic-handler-test.js
The `cdnProvider` param as of now accepts a string. A support to pass `cdnProvider` as a function is handled here.
Fixes https://github.com/quintype/ace-planning/issues/144
Documentation: Have added in `routes.js` file with reference to the cdnProvider
=> Cdnprovider

package-lock.json, package.json, server/amp/handlers/story-page.js, server/amp/helpers/get-domain-specific-opts.js, test/integration/amp-handler-test.js
changes:
- take config from `publisher.yml` (i.e. blacknight config) and give it as `additionalConfig` to amplib
- change api of `opts.getAdditionalConfig` (This might need a change in documentation)
=> Pb integration amogh

README.md, package-lock.json, package.json, server/visual-stories.js, test/integration/visual-story-test.js
=> fix(visual-stories): Revert visual story 🔨

package-lock.json, package.json
https://github.com/quintype/quintype-amp/issues/318
This PR bumps ampLib version to take the newly implemented table story element
=> Amp table element

package-lock.json, package.json, server/data-loader-helpers.js
Update node backend version - add read time attribute in default story fields
=> chore: Update node backend version

package-lock.json, package.json, server/handlers/isomorphic-handler.js, server/impl/light-page-impl.js, server/routes.js, test/integration/isomorphic-handler-test.js
Closes https://github.com/quintype/frontend-worker/issues/20
=> fix(amp): Implement toggle to encode slug :zap:

server/amp/handlers/story-page.js
closes https://github.com/quintype/madrid/issues/3465
=> fix(amp): Fix related stories across domains :hammer:

package-lock.json, package.json
update packages:
- websocket-extensions from 0.1.3 to 0.1.4
- standard-version from 5.0.2 to 8.0.1 
- tree-kill from 1.2.1 to 1.2.2
=> Upgrade package

package-lock.json, package.json
backend version to support default story limit Please include the summary of the change made. Please include the required context here. Please include the issue reference for the fix and the dependencies reference for the change.
Fixes # https://github.com/quintype/ace-planning/issues/18
=> update: backend version to support default story limit 

package-lock.json, package.json
This PR gets the latest version of the `quintype/ampv2.4.1` which has the fix for amp encoding errors reported by AFK and TQ.
Dependencies: https://github.com/quintype/quintype-amp/pull/338
Documentation: NA
=> Amp validation error

server/handlers/story-redirect.js
Fixes https://github.com/quintype/madrid/issues/3696
=> fix: uppercase story slug redirection

package-lock.json, package.json
Ticket - https://github.com/quintype/ace-planning/issues/349
=> feat: support custom style for visual story

package-lock.json, package.json
update quintype-node-components library version
=> fix(update) : update quintype-node-components lib

package-lock.json, package.json
Support image attribution and caption  on visual story
quintype/ace-planning#287
=> fix(visual story) : Update amp version to  support image attribution and caption 

package-lock.json, package.json, server/handlers/custom-route-handler.js, server/handlers/isomorphic-handler.js
Vikatan requested a cookie-based recommendation from the server side. 
Solution: 
Added support for cookies in load data function, used req.cookies, and passing inside the load data.
Ticket - https://github.com/quintype/ace-planning/issues/470
docs - https://developers.quintype.com/malibu/tutorial/creating-a-page.html
=> Feat(Cookies): Added support for cookies in load data function ⚡ 

server/routes.js
Update the docs for custom TTL
=> fix(doc) :  Update the docs for custom TTL

package-lock.json, package.json
update backend version to fix request function error management
Fixes: https://github.com/quintype/ace-planning/issues/507
=> fix: update backend version

client/service-worker-helper.js, package-lock.json, package.json
Fixes https://github.com/quintype/quintype-node-framework/issues/201
Changes in Ahead : https://github.com/quintype/madrid/pull/3976
=> deps(MAJOR): bump workbox from 2.1.1 to 6.2.0 via CDN

package-lock.json, package.json, server/data-loader-helpers.js
added a prop which accepts an array of index, which is used to get the collection of collection of stories for those collections which matches the index
=> feat: support collection of collection of stories data based on index

package-lock.json, package.json
Reference : https://github.com/quintype/ace-planning/issues/582
=> bump amp version

package-lock.json, package.json, server/amp/helpers/infinite-scroll.js, test/unit/amp/infinite-scroll-helper.js
https://github.com/quintype/ace-planning/issues/596
=> fix: remove visual stories from amp infinite scroll

package-lock.json, package.json
Added a new feature to toggle webengage in quintype amp
Updated the quintype-amp version with the above changes
=> Updated quintype-amp version

package-lock.json, package.json
quintype-amp PR reference: https://github.com/quintype/quintype-amp/pull/367
=> Add parcel as devDependency in quintype-amp

package-lock.json, package.json
Reference: https://github.com/quintype/ace-planning/issues/618
=> Caption and Attribution alignment issue in amp pages

README.md, client/start.js, package-lock.json, package.json, server/handlers/fcm-registration-handler.js, server/routes.js
Fixes - https://github.com/quintype/madrid/issues/4372
Will update the doc soon.
=> fix(fcm): Support fcm integration keys from PB config

package-lock.json, package.json, server/amp/handlers/story-page.js
Fixes - https://github.com/quintype/madrid/issues/4575
=> fix(amp): Incorrect localised content displayed across publishers

package-lock.json, package.json, server/routes.js
Fixes - https://github.com/quintype/madrid/issues/4565
=> fix(TTL) : Exclude RSS feeds and advanced search API from custom cache TTL

package-lock.json, package.json, server/handlers/custom-route-handler.js
Fixes - https://github.com/quintype/page-builder/issues/1636
=> feat(SEO) : Support SEO Metadata in static pages

package-lock.json, package.json
Take amplib fix for https://github.com/quintype/madrid/issues/4597
=> Amp word wrap fix

package-lock.json, package.json
Add new version of Amp lib
ACE => https://github.com/quintype/ace-planning/issues/589
AMP => https://github.com/quintype/quintype-amp/pull/383
=> Beta amp cta

package-lock.json, package.json
Add. new version of amp with logo url width changes
=> Add. new version of amp with logo url width changes

package-lock.json, package.json, server/amp/helpers/infinite-scroll.js, test/unit/amp/infinite-scroll-helper.js
**Reverted Whitelisting of origin changes** 
Passing absoluteUrl to amp-next-page "src" attribute &
Added Unit tests for relatesStoriesApi / CustomApi
https://github.com/quintype/ace-planning/issues/678
=> Includes =>  AbsoluteUrl to amp-next-page "src" attribute & Unit tests for relatesStoriesApi / CustomApi

package-lock.json, package.json
Reference: https://github.com/quintype/ace-planning/issues/710
=> feat: remove powered by quintype from the footer 

package-lock.json, package.json
Reference: https://github.com/quintype/quintype-amp/issues/398
=> add height and width to amp-video to remove amp validation errors

package-lock.json, package.json
Reference : https://github.com/quintype/ace-planning/issues/723
=>  fix: pass domain value to chartbeat

package-lock.json, package.json
=> chore(deps): bump amp to support new dm subtype

package-lock.json, package.json, server/handlers/isomorphic-handler.js
=> feat(amp): Decode embed using utf 8

package-lock.json, package.json
Fixes - https://github.com/quintype/page-builder/issues/2148
=> fix(update components) : Youtube thumbnail fix

package-lock.json, package.json
=> chore(deps):  use  components 3.3.0

client/start.js, package-lock.json, package.json
Check [comment](https://github.com/quintype/page-builder/issues/2161#issuecomment-1384942503)
fixes https://github.com/quintype/page-builder/issues/2161
=> fix(ga): update title before history push for ga tracking issue

package-lock.json, package.json
https://github.com/quintype/page-builder/issues/2226
=> Adsense amp

package-lock.json, package.json
=> chore: bump arrow for custom timestamp support

package-lock.json, package.json
https://github.com/quintype/madrid/issues/4822
=> chore: update amp to support last published time

package-lock.json, package.json, server/handlers/custom-route-handler.js
Add metadata to the static page load data. 
Ref ticket: https://github.com/quintype/ace-planning/issues/828
=> Add metadata to static page data

package-lock.json, package.json
Add-  - Amp lib beta version - include changes - Picking Scrolling attribute from BOLD to fix the iframe - scroller issue in amp page ,
https://github.com/quintype/ace-planning/issues/836
https://github.com/quintype/quintype-amp/pull/431
=> Iframe scroll issue 

package-lock.json, package.json
Ref ticket: https://github.com/quintype/quintype-amp/issues/429
Ref amp PR: https://github.com/quintype/quintype-amp/pull/435
Ref malibu PR: https://github.com/quintype/malibu-advanced/pull/516
=> Add Support for AMP GA4

package-lock.json, package.json
https://github.com/quintype/ace-planning/issues/866
=> bump amplib to take story element slots

package-lock.json, package.json
https://github.com/quintype/page-builder/issues/2409
bump amplib to take GA4 AMP rework changes
=> Ga4 rework

package-lock.json, package.json
Ref ticket: https://github.com/quintype/ace-planning/issues/852
Fix:
Add word break and font family to title tag
=> [fix]: Truncation of amp VS title 

package-lock.json, package.json
Ref ticket: https://github.com/quintype/ace-planning/issues/874
=> [feat]: Support MGID auto ads in AMP

package-lock.json, package.json
https://github.com/quintype/ace-planning/issues/810
https://github.com/quintype/quintype-amp/pull/428
=> Image bandwidth consumption issue

package-lock.json, package.json
=> bump(amp): support brightcove with default player-id

package-lock.json, package.json
=> fix(update amp version) : author card refactor

package-lock.json, package.json, server/redirect-url-helper.js
Fixes - https://github.com/quintype/page-builder/issues/2495
=> fix(500 error) :  When a random redirection is added from PB, the site throws a 500 internal error.

package-lock.json, package.json
ref ticket: https://github.com/quintype/ace-planning/issues/897
=> [fix]: Amp font render issue

package-lock.json, package.json
Ref ticket: https://github.com/quintype/ace-planning/issues/877
Malibu Pr: https://github.com/quintype/malibu-advanced/pull/550
AMp PR : https://github.com/quintype/quintype-amp/pull/459
=> fix(amp): Redesign HeroImage caption and attribution 

package-lock.json, package.json
ref: https://github.com/quintype/page-builder/issues/2704
=> fix(images): Impose size restriction to 640 across images

package-lock.json, package.json, server/amp/handlers/infinite-scroll.js, server/amp/handlers/story-page.js, server/amp/helpers/get-amp-page-base-path.js, server/amp/helpers/infinite-scroll.js, server/handlers/isomorphic-handler.js, server/impl/light-page-impl.js, server/routes.js, test/integration/amp-handler-test.js
https://github.com/quintype/page-builder/issues/2737
This path has to be passed inside featureConfig. It can passed as a `function` or a `string`
```
featureConfig: {
ampPageBasePath: () => "/amp"
}
```
=> feat: add support to configure amp story page path through featureConfig

package-lock.json, package.json, server/handlers/isomorphic-handler.js, server/routes.js, test/integration/isomorphic-handler-test.js
Reference: https://github.com/quintype/ace-planning/issues/1000
=> feat(external id): add support to retrieve stories with external ids

package-lock.json, package.json
=> fix(bulk request): POST bulk to a get

package-lock.json, package.json, server/generate-routes.js
Ticket: https://github.com/quintype/page-builder/issues/2828
Added an extra param to support PB preview functionality.
=> added params for the section pages route

package-lock.json, package.json
https://github.com/quintype/ace-planning/issues/1025
https://github.com/quintype/quintype-node-seo/pull/556
=> feat(Default Collection): Avail Canonical Url field for Default Collections #556

server/redirect-url-helper.js
=> improve log on redirection failure

server/redirect-url-helper.js
Reverts quintype/quintype-node-framework#419
=> Revert "improve log on redirection failure"

package-lock.json, package.json, server/amp/handlers/infinite-scroll.js, server/redirect-url-helper.js
fixes: https://github.com/quintype/page-builder/issues/3031#event-12355373140
=> fix( infinite-scroll amp): handle errors in infinite-scroll amp api response

package-lock.json, package.json
Ticket: https://github.com/quintype/page-builder/issues/2963
=> feat: Support for Videos on Visual (amp) Stories 

package-lock.json, package.json
Ticket: https://github.com/quintype/page-builder/issues/2957
SEO PR: https://github.com/quintype/ahead/pull/965
=> fix: updated version of seo for author schema

package-lock.json, package.json
=> [feat]: Support alt text in amp

package-lock.json, package.json, server/redirect-url-helper.js
fix: https://github.com/quintype/page-builder/issues/3142
=> feat: Add support for 410 Gone URL 

package-lock.json, package.json, server/amp/handlers/story-page.js
Ticket: https://github.com/quintype/page-builder/issues/3189
=> feat(auto advance cards): auto advance images and videos in  visual stories

package-lock.json, package.json
https://github.com/quintype/page-builder/issues/2629
=> bump amplib

package-lock.json, package.json, server/amp/handlers/story-page.js
fix: https://github.com/quintype/madrid/issues/5519
=> fix(Amp story): pass amp optimizer toggle to preload hero image

package-lock.json, package.json
https://github.com/quintype/page-builder/issues/3418
=> fix(publish time): fix amp publish time

package-lock.json, package.json, server/amp/handlers/story-page.js
Ticket: https://github.com/quintype/page-builder/issues/3467
=> fix(cache-tags): fix amp cache tags

server/amp/handlers/story-page.js
Ticket: https://github.com/quintype/page-builder/issues/3502
Reference ticket: https://github.com/quintype/page-builder/issues/3467#issuecomment-2428892837
=> fix(amp ttl): increase amp ttl

server/amp/handlers/story-page.js
Reverting previous commit where cdn-ttl is increased
=> revert amp ttl change

package-lock.json, package.json, server/amp/handlers/story-page.js
Ticket: https://github.com/quintype/page-builder/issues/3502
=> Increase amp ttl

package-lock.json, package.json, server/data-loader-helpers.js, server/generate-routes.js, test/unit/generate-routes-test.js
fix: https://github.com/quintype/page-builder/issues/3404
=> feat(Preview): support home & collection preview route

.vscode/settings.json, bin-dev-scripts/standard-version-release.sh, package-lock.json, package.json, server/api-client.js, server/publisher-config.js, server/routes.js, server/start.js
closes: https://github.com/quintype/page-builder/issues/2696
=> feat(host_to_api): Implement host to api mapping ⚡ 

package-lock.json, package.json, server/routes.js
fix: https://github.com/quintype/page-builder/issues/3595
=> feat(CORS): whitelist quintype.com

package-lock.json, package.json, server/handlers/isomorphic-handler.js
fix: https://github.com/quintype/page-builder/issues/3506
=> fix(Static routes): support 404 if no loader

package-lock.json, package.json
fix: https://github.com/quintype/madrid/issues/5666
=> fix: Preload visual hero image
