quintype/quintype-node-framework

.gitignore, client/impl/load-service-worker.js, package-lock.json, package.json, server/handlers/generate-service-worker.js, test/unit/load-service-worker-test.js
When a config is updated from secret mode to itsman, the service worker needs to update itself to serve the updated shell to reflect the change on the UI.
The above is done by comparing the timestamp of the uploaded configuration and that of which is set globally in the client.
=> Cache burst based on config upload time

package-lock.json, package.json, server/impl/api-client-impl.js
the latest version of @quintype/backend removes vulnerable dependency
cryptiles
=> uses @quintype/backend instead of quintype-backend

server/start.js
- SIGHUP will gracefully kill spawn new workers, and gracefully kill the old ones
- SIGTERM will be sent by kube when it is deploying. This can be caught to gracefully exit
=> feat(Server): Implement SIGHUP and SIGTERM handler

CHANGELOG.md, bin-dev-scripts/standard-version-release.sh, package-lock.json, package.json
=> feat(pre-publish script): Add pre-publish shell script to support standard-version prerelease 

README.md, server/generate-routes.js, test/unit/generate-routes-test.js
generateCommonRoutes deprecates the old generateSectionRoutes and generateStoryRoutes. It comes with multi domain support, and takes the section paths from the editor itself.
=> feat(Multi Domain): Adding a function called generateCommonRoutes

server/handlers/custom-route-handler.js
https://ace-web.qtstage.io/about-us returns a configured static page as opposed to https://ace-web.qtstage.io/about-us/ returning a 404
handle trailing slash if any for static pages ex : https://ace-web.qtstage.io/about-us/ and return relevant results
check if the path ends with a `/` strip if true
=> fix(customRouteHandler): Remove trailing slash if any for static pages :bug:

client/impl/fcm.js
fix made to receive token from api call using **fetch**. Since **global.wretch** is not present in all existing publishers
=> fix (fcm): replaced global.wretch by fetch in registerFCMTopic

package-lock.json, package.json, server/amp-helpers.js, test/integration/amp-handler-test.js, test/unit/amp-setcorsheaders-test.js
https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests
we have a helper function to set CORS headers. Valid CORS requests can come from
1. google/bing CDN
2. subdomains
3. google/bing CDN of subdomains
I had missed out google/bing CDN of subdomains, so adding that to whitelist in this PR. Also, added unit tests for the setCorsHeaders helper function (since we might use it later for other stuff, not just infinite scroll)
=> test: setCorsHeaders unit tests

server/amp/handlers/story-page.js, test/unit/amp/amp-get-domain-specific-opts.js, test/unit/amp/amp-setcorsheaders-test.js, test/unit/amp/amp-story-page-handler.js
Found that `ampStoryPageHandler` was mutating the `opts` object passed to it. This wasn't a problem for custom publishers since `opts` comes from publisher app and will remain same. But in case of ahead it's a problem since opts belonging to one ahead publisher was being passed to another ahead publisher.
Because of this, things like related stories etc. of one ahead publisher were being shown to a different ahead publisher. Bad!
https://github.com/quintype/ace-planning/issues/259
Bug fix (non-breaking change which fixes an issue)
Wrote a test to check that `ampStoryPageHandler` no longer mutates opts
=> fix(AMP): Implement AMP Story Page Handler ⚡ 

package-lock.json, package.json, server/amp/handlers/story-page.js, test/data/amp-test-data.js, test/integration/amp-handler-test.js, test/unit/amp/amp-story-page-handler.js
Platform sends a field `is-amp-supported` in the story API. If `is-amp-supported` was false, we were showing a banner telling the reader that the story is not AMP supported.
Relying on platform's `is-amp-supported` didn't make sense anymore since AMP pages are now handled by amplib. So we moved this logic to ampLib.
Added a helper function called `unsupportedStoryElementsPresent` in amplib for this purpose.
https://github.com/quintype/ace-planning/issues/336
https://github.com/quintype/quintype-amp/pull/337
Added following integration tests for ampStoryPageHandler:
- should redirect to non-amp page if story contains unsuported elements and invalid-elements-strategy in /api/v1/amp/config is set to redirect-to-web-version
- should show amp page …
=> Amp move is amp supported

package-lock.json, package.json, server/impl/api-client-impl.js, test/unit/api-client-test.js
First 4 Story tags were used as cache tags for an automated collection. However an automated collection can have N number of stories and collections under it and new items can be added at any time. So using story tags as cache tags is not extensible and error prone.
To fix this, instead of stories we are including the rules that make up the automated collection. And whenever a story matching a rule gets published it's corresponding rule tag also gets purged. That way all the automated collections that depend on this rule tag gets invalidated.
https://github.com/quintype/itsman/issues/7411
Please describe the …
=> adds ability to include cache tags based on its rules for an automated collection

package-lock.json, package.json
one of the reasons for https://github.com/quintype/ace-planning/issues/415
=> fix: bump amplib to take invalidBanner fix

package-lock.json, package.json, server/amp/handlers/visual-stories-bookend.js, server/handlers/cdn-caching.js, server/handlers/custom-route-handler.js, server/handlers/isomorphic-handler.js, server/handlers/story-redirect.js, server/routes.js, test/integration/custom-route-handler-test.js, test/integration/isomorphic-data-load-test.js, test/integration/isomorphic-handler-test.js, test/integration/url-redirect-test.js
Added ability to override s-maxage cache-control headers, in order to override it, publishers need to send `ttlCacheControl` values in `isomorphicRoutes()` from the app level.  if `ttlCacheControl` not present the default values of `s-maxage` will be 900 seconds as previous.
Also removed `Surrogate-Control`  from headers as its values were different from other CDN and it may override the actual cache-control values.
Fixes #  https://github.com/quintype/ace-planning/issues/416
Dependencies # NA
=> Fix(cdn-caching): Added support for custom TTL cache values

package-lock.json, package.json
`@ampproject/toolbox-optimizer` version 2.8.1 throws the following error, so locking it to v2.8.0
```
Error: [object Object] is not a PostCSS plugin
at Processor.normalize (/Users/amogh/work/qt/thequint-malibu/node_modules/postcss/lib/processor.es6:130:15)
at new Processor (/Users/amogh/work/qt/thequint-malibu/node_modules/postcss/lib/processor.es6:38:25)
at postcss (/Users/amogh/work/qt/thequint-malibu/node_modules/postcss/lib/postcss.es6:34:10)
at module.exports (/Users/amogh/work/qt/thequint-malibu/node_modules/cssnano-simple/src/index.js:54:10)
at Processor.normalize (/Users/amogh/work/qt/thequint-malibu/node_modules/@ampproject/toolbox-optimizer/node_modules/postcss/lib/processor.js:40:13)
at new Processor (/Users/amogh/work/qt/thequint-malibu/node_modules/@ampproject/toolbox-optimize …
```
=> fix(optimizer): Lock amp optimizer to v2.8.0 🔨 

package-lock.json, package.json, server/routes.js, test/integration/sketches-proxy-test.js
It is observed that the below requests have a short TTL. We need to add the custom TTL on these
Eg: "/api/*, /sitemap/*, /rss-feed" etc.
Note: do not override `s-maxage`  for breaking news, qlitics and if  the cacheability is Private
Fetch the s-maxage value from BK for both isomorphic and upstream routes.
https://github.com/quintype/ace-planning/issues/488
=> fix(TTL) :  Support overriding of response cache header s-maxage  from  Sketches Proxy ⚡ 

package-lock.json, package.json
Updated Quintype amp dependencies from 2.4.11 to 2.4.12. 
Ticket - https://github.com/quintype/ace-planning/issues/558
=> chore(dep): bump quintype amp dependencies from 2.4.11 to 2.4.12 ⚡

package-lock.json, package.json, server/routes.js
Exclude `/api/instant-articles.rss` from adding cache tags
=> Rss hotfix

package-lock.json, package.json, server/caching.js, test/integration/custom-route-handler-test.js, test/integration/url-redirect-test.js, test/unit/api-client-test.js
ref: https://github.com/quintype/ace-planning/issues/814
Check the cache tag and surrogate keys on response headers for custom url routes.
it should be `sp/1/123 `and not `u/1/123`
=> fix:  custom pages cache

package-lock.json, package.json, server/handlers/cdn-caching.js, test/integration/isomorphic-handler-test.js
This `unsafe-inline` keyword was allowing inline scripts to be executed on the page. This is considered a security risk as it makes the page vulnerable to cross-site scripting attacks.
We need to remove all those keywords and add this
`script-src 'self' https://cdnjs.cloudflare.com/`
to be safe.
Ref ticket: https://github.com/quintype/ace-planning/issues/797
1. Open frontend url 
2. open inspector and click on network tab
3. check for headers of the main route.
4. Inside the header, in content-security-policy, you need find `'self' https://cdnjs.cloudflare.com/ `in `script-src `
=> Fix vulnerability in content-security-policy

package-lock.json, package.json, server/handlers/cdn-caching.js, server/handlers/isomorphic-handler.js
fixes https://github.com/quintype/page-builder/issues/2395
Context: platform doesn't have dedicated CDN cache keys for topic pages so FE was receiving stale data. So hardcoding a ttl of 10 min until platform makes a fix
=> hardcode ttl of 10min for topic page

package-lock.json, package.json
we have search page on the header for normal pages which directs the user to the search page. The client (praja vani) wants the same to be replicated for AMP as well .
https://github.com/quintype/ace-planning/issues/841#event-9196522028
https://github.com/quintype/quintype-amp/pull/433
=> Add render prop for Navbar-Header in AMP lib to add customizations from FE

package-lock.json, package.json
TPML was facing an issue for migrated stories where image metadata is not matching with actual image dimension, thats when hero image is stretched on AMP.
https://github.com/quintype/ace-planning/issues/839
https://github.com/quintype/quintype-amp/pull/437
=> Image stretch issue on AMP

package-lock.json, package.json, server/handlers/cdn-caching.js, server/handlers/custom-route-handler.js, server/handlers/isomorphic-handler.js, server/handlers/story-redirect.js, server/routes.js, test/integration/sketches-proxy-test.js
`opts.maxAge` Support overriding of proxied response cache header `maxage` from Sketches. For Breaking News and if the cacheability is Private, it is not overwritten instead the cache control will be the same as how it's set in sketches. We can set `upstreamRoutesMaxage: 15` under `publisher` in publisher.yml config file that comes from BlackKnight or pass maxAge as a param.
`maxAge` Overrides the max-age value, the default value is set to 15 seconds. We can set `isomorphicRoutesMaxage: 15` under `publisher` in publisher.yml config file that comes from BlackKnight or pass maxAge as a param.
Add customization for max age
Please delete options that are not …
=> Add support for custom max-age value

constants.js, package-lock.json, package.json, server/amp/handlers/story-page.js, server/caching.js, server/routes.js, test/integration/amp-handler-test.js, test/unit/amp/amp-story-page-handler.js
Reference: https://github.com/quintype/ace-planning/issues/988
This pr adds a feature to support disabling amp for a particular story.
Client has to create a story attribute with the slug "disable-amp-for-single-story" and set its value to true to enable this feature. When that attribute is set to true we redirect back to the non-amp page without creating an amp version for that story.
=> feat(amp): disable amp for a particular story

package-lock.json, package.json, server/routes.js, test/integration/sketches-proxy-test.js
Fixes : https://github.com/quintype/page-builder/issues/3419
=> [fix]: enable wildcard api route for sketches proxy
